# Generated by Django 4.2 on 2024-09-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/imgres?q=placeholder%20food%20image&imgurl=https%3A%2F%2Fcdn.dribbble.com%2Fusers%2F1012566%2Fscreenshots%2F4187820%2Fmedia%2F985748436085f06bb2bd63686ff491a5.jpg%3Fresize%3D400x0&imgrefurl=https%3A%2F%2Fdribbble.com%2Fwhomohit&docid=6G4983f15vRFnM&tbnid=y4RSZyUgqUsUiM&vet=12ahUKEwj5r5XCwOOIAxWXkq8BHSGXBZ8QM3oFCIABEAA..i&w=400&h=300&hcb=2&ved=2ahUKEwj5r5XCwOOIAxWXkq8BHSGXBZ8QM3oFCIABEAA', max_length=500),
        ),
    ]
